### ISSUE TITLE
Unused imports trigger even if included in __all__.

### ISSUE THREAD

**Issue by bdice** [MarcoGorelli/cython-lint#80]
For flake8, an import is considered "used" if it appears in a module's `__all__`. It seems that cython-lint is unaware of `__all__` when considering which imports are used or unused.

Example:

```python
# file.pyx
import numpy

__all__ = ["numpy"]
```

```bash
$ cython-lint file.pyx
file.pyx:1:8: 'numpy' imported but unused
```

Rename the above to `file.py` -- flake8 is clean.
Renaming the above to `file.py` and remove `__all__`:
```bash
$ flake8 file.py
file.py:1:1: F401 'numpy' imported but unused
```

**Comment by MarcoGorelli** [comment]
yup, thanks for the report!

**Comment by MarcoGorelli** [comment]
finally done, sorry this took a while
