### ISSUE TITLE
Triple quotes

### ISSUE THREAD

**Issue by lyzlisa** [MarcoGorelli/cython-lint#83]
Does `double-quote-cython-strings` handle conversion of `'''` to `"""` in docstrings or multiline strings?

**Comment by MarcoGorelli** [comment]
hey - I can't remember, did you try it to see?

**Comment by lyzlisa** [comment]
When I ran `pre-commit run double-quote-cython-strings -a` only the single quotes got updated.

Looking at the code, I'm guessing it's currently not supported?

https://github.com/MarcoGorelli/cython-lint/blob/346d25894652a17f4cc7514f4d832f2041fc2c2e/cython_lint/string_fixer.py#L11-L12

**Comment by MarcoGorelli** [comment]
looks like it

closing then, but thanks for the issue
