### ISSUE TITLE
Question: Adding to SublimeText

### ISSUE THREAD

**Issue by YoSTEALTH** [MarcoGorelli/cython-lint#95]
This is awesome, finally a lint for Cython!!!

How to go about making this work with SublimeText?

**Comment by MarcoGorelli** [comment]
thanks! what do I need to do for that?

**Comment by YoSTEALTH** [comment]
@MarcoGorelli http://www.sublimelinter.com/en/master/index.html

**Comment by YoSTEALTH** [comment]
@MarcoGorelli https://github.com/SublimeLinter/SublimeLinter/discussions/1925

**Comment by MarcoGorelli** [comment]
not sure what I have to do here, but I'd take a PR if you wanted to make one if anything needs to change on cython-lint's side

**Comment by MarcoGorelli** [comment]
closing then, but feel to make a PR either here or to sublime, happy to help out if needed
