### ISSUE TITLE
[CI/CD] Update publishing to PyPI w/ tokenless

### ISSUE THREAD

**Issue by webknjaz** [MarcoGorelli/cython-lint#97]
Here's the up-to-date guide: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.
Also, separate building from publishing due to security considerations.

**Comment by MarcoGorelli** [comment]
thanks!

**Comment by webknjaz** [comment]
@MarcoGorelli any feedback on trusted publishing? Was it well-explained?

**Comment by MarcoGorelli** [comment]
yup, thanks!
